export type RunStatus='PENDING'|'QUEUED'|'RUNNING'|'PASSED'|'FAILED'|'CANCELLED'|'TIMED_OUT'|'ERROR';
export type StepType='NAVIGATE'|'CLICK'|'FILL'|'SELECT'|'ASSERT_TEXT'|'ASSERT_VISIBLE'|'ASSERT_URL'|'WAIT'|'SCREENSHOT'|'API_REQUEST'|'KEYBOARD'|'SCROLL'|'HOVER'|'CUSTOM';
