import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, ArrowLeft, FolderPlus, Globe2, Pencil, Plus, RefreshCw, Workflow } from 'lucide-react';
import { sharedStepsApi } from '@/lib/api';
import { Button } from '@/components/ui/Button';
import { Card, CardContent } from '@/components/ui/Card';
import { Modal } from '@/components/ui/Modal';
import { PageSpinner } from '@/components/ui/Spinner';
import { toast } from '@/components/ui/Toast';

type SharedStep = { id: string; name: string; description: string | null; projectId: string | null; folderId?: string | null; version: number; isArchived: boolean; steps: Array<Record<string, unknown>>; parameters: Array<{ key: string; required?: boolean; secret?: boolean }>; _count?: { referencesTo: number } };
type Folder = { id: string; name: string; projectId: string | null; parentId: string | null };

const starterSteps = [{ index: 0, name: 'Navigate to home', type: 'NAVIGATE', input: { url: '/' } }];

export function SharedStepsPage() {
  const { projectId } = useParams();
  const qc = useQueryClient();
  const [showArchived, setShowArchived] = useState(false);
  const [editing, setEditing] = useState<SharedStep | null>(null);
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [folderId, setFolderId] = useState('');
  const [stepsJson, setStepsJson] = useState(JSON.stringify(starterSteps, null, 2)); const [paramsJson, setParamsJson] = useState('[]'); const [formError, setFormError] = useState('');
  const [folderName, setFolderName] = useState(''); const [dependentsId, setDependentsId] = useState<string | null>(null);
  const { data = [], isLoading } = useQuery<SharedStep[]>({ queryKey: ['shared-steps', projectId, showArchived], queryFn: () => sharedStepsApi.list(projectId!, showArchived), enabled: !!projectId });
  const { data: folders = [] } = useQuery<Folder[]>({ queryKey: ['shared-step-folders', projectId], queryFn: () => sharedStepsApi.folders(projectId!), enabled: !!projectId });
  const { data: dependents } = useQuery<{ tests: Array<{ id: string; name: string }>; directOrNestedSharedSteps: number }>({ queryKey: ['shared-step-dependents', projectId, dependentsId], queryFn: () => sharedStepsApi.dependents(projectId!, dependentsId!), enabled: !!dependentsId });
  const refresh = () => { qc.invalidateQueries({ queryKey: ['shared-steps', projectId] }); qc.invalidateQueries({ queryKey: ['shared-step-folders', projectId] }); };
  const openCreate = () => { setEditing({ id: '', name: '', description: '', projectId: projectId ?? null, version: 0, isArchived: false, steps: starterSteps, parameters: [] }); };
  useEffect(() => { if (!editing) return; setName(editing.name); setDescription(editing.description ?? ''); setFolderId(editing.folderId ?? ''); setStepsJson(JSON.stringify(editing.steps, null, 2)); setParamsJson(JSON.stringify(editing.parameters ?? [], null, 2)); setFormError(''); }, [editing]);
  const save = useMutation({ mutationFn: () => {
    const body = { name, description: description || undefined, folderId: folderId || null, steps: JSON.parse(stepsJson), parameters: JSON.parse(paramsJson) };
    return editing?.id ? sharedStepsApi.update(projectId!, editing.id, body) : sharedStepsApi.create(projectId!, body);
  }, onSuccess: () => { refresh(); setEditing(null); toast.success('Shared step saved'); }, onError: (error: Error) => setFormError(error.message || 'Unable to save shared step') });
  const archive = useMutation({ mutationFn: (id: string) => sharedStepsApi.archive(projectId!, id), onSuccess: refresh, onError: () => toast.error('Unable to archive shared step') });
  const promote = useMutation({ mutationFn: (id: string) => sharedStepsApi.promote(projectId!, [id]), onSuccess: () => { refresh(); toast.success('Promoted to organisation library'); }, onError: () => toast.error('Promotion requires an organisation admin') });
  const createFolder = useMutation({ mutationFn: () => sharedStepsApi.createFolder(projectId!, { name: folderName }), onSuccess: () => { setFolderName(''); refresh(); toast.success('Folder created'); }, onError: () => toast.error('Unable to create folder') });
  const submit = () => { try { JSON.parse(stepsJson); JSON.parse(paramsJson); setFormError(''); save.mutate(); } catch { setFormError('Steps and parameters must contain valid JSON'); } };
  if (isLoading) return <PageSpinner />;
  return <div className="max-w-6xl mx-auto px-4 py-7 space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><Link to={`/projects/${projectId}/tests`} className="text-xs inline-flex items-center gap-1 mb-2 text-slate-400 hover:text-white"><ArrowLeft size={13} /> Tests</Link><h1 className="text-2xl font-semibold text-white">Shared Steps</h1><p className="text-sm text-slate-400 mt-1">Live reusable flows. New runs snapshot resolved steps for audit-safe history.</p></div><div className="flex gap-2"><Button variant="secondary" size="sm" onClick={() => setShowArchived(v => !v)}><Archive size={13} /> {showArchived ? 'Hide archived' : 'Show archived'}</Button><Button size="sm" onClick={openCreate}><Plus size={13} /> New shared step</Button></div></div>
    <Card><CardContent className="p-3 flex gap-2 items-center"><FolderPlus size={15} className="text-violet-300" /><input value={folderName} onChange={e => setFolderName(e.target.value)} placeholder="New project folder" className="flex-1 rounded-md px-3 py-1.5 bg-white/5 border border-white/10 text-white text-xs" /><Button size="sm" variant="secondary" disabled={!folderName.trim()} loading={createFolder.isPending} onClick={() => createFolder.mutate()}>Add folder</Button>{folders.length > 0 && <span className="text-xs text-slate-500">{folders.filter(folder => folder.projectId).map(folder => folder.name).join(' · ')}</span>}</CardContent></Card>
    <div className="grid gap-3">{data.map(step => <Card key={step.id}><CardContent className="p-4 flex flex-wrap gap-4 items-center justify-between"><div><div className="flex gap-2 items-center"><Workflow size={16} className="text-violet-300" /><strong className="text-sm text-white">{step.name}</strong><span className="text-[10px] rounded px-1.5 py-0.5 bg-white/5 text-slate-400">{step.projectId ? 'PROJECT' : 'ORG GLOBAL'}</span>{step.isArchived && <span className="text-[10px] text-amber-300">ARCHIVED</span>}</div><p className="text-xs text-slate-400 mt-1">{step.steps.length} steps · v{step.version} · {step._count?.referencesTo ?? 0} direct references{step.description ? ` · ${step.description}` : ''}</p></div><div className="flex gap-2">{!step.isArchived && <Button variant="secondary" size="sm" onClick={() => setEditing(step)}><Pencil size={13} /> Edit</Button>}<Button variant="secondary" size="sm" onClick={() => setDependentsId(step.id)}>Dependents</Button>{step.projectId && !step.isArchived && <Button variant="secondary" size="sm" loading={promote.isPending} onClick={() => promote.mutate(step.id)}><Globe2 size={13} /> Promote</Button>}{!step.isArchived && <Button variant="secondary" size="sm" loading={archive.isPending} onClick={() => archive.mutate(step.id)}><Archive size={13} /> Archive</Button>}</div></CardContent></Card>)}{data.length === 0 && <Card><CardContent className="p-10 text-center text-sm text-slate-500"><RefreshCw size={20} className="mx-auto mb-2" />No shared steps yet.</CardContent></Card>}</div>
    {editing && <Modal open onClose={() => setEditing(null)} title={editing.id ? `Edit ${editing.name}` : 'New shared step'} size="xl"><div className="space-y-3"><input value={name} onChange={e => setName(e.target.value)} placeholder="Shared step name" className="w-full rounded-md px-3 py-2 bg-white/5 border border-white/10 text-white text-sm" /><input value={description} onChange={e => setDescription(e.target.value)} placeholder="Description" className="w-full rounded-md px-3 py-2 bg-white/5 border border-white/10 text-white text-sm" /><select value={folderId} onChange={e => setFolderId(e.target.value)} className="w-full rounded-md px-3 py-2 bg-white/5 border border-white/10 text-white text-sm"><option value="">No folder</option>{folders.filter(folder => folder.projectId).map(folder => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select><label className="block text-xs text-slate-400">Parameters JSON</label><textarea value={paramsJson} onChange={e => setParamsJson(e.target.value)} rows={5} className="w-full rounded-md px-3 py-2 bg-black/20 border border-white/10 text-white text-xs font-mono" /><label className="block text-xs text-slate-400">Steps JSON. Use `SHARED` references for nested flows.</label><textarea value={stepsJson} onChange={e => setStepsJson(e.target.value)} rows={12} className="w-full rounded-md px-3 py-2 bg-black/20 border border-white/10 text-white text-xs font-mono" />{formError && <p className="text-xs text-red-300">{formError}</p>}<div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setEditing(null)}>Cancel</Button><Button loading={save.isPending} disabled={!name.trim()} onClick={submit}>Save shared step</Button></div></div></Modal>}
    {dependentsId && <Modal open onClose={() => setDependentsId(null)} title="Shared step dependents" size="md"><p className="text-xs text-slate-400 mb-3">{dependents?.directOrNestedSharedSteps ?? 0} nested shared definitions and {dependents?.tests.length ?? 0} affected tests.</p><div className="space-y-2">{dependents?.tests.map(test => <Link key={test.id} to={`/projects/${projectId}/tests/${test.id}/edit`} className="block rounded bg-white/5 px-3 py-2 text-sm text-violet-200">{test.name}</Link>) ?? <p className="text-sm text-slate-500">Loading...</p>}</div></Modal>}
  </div>;
}
